server:
  port: ${PORT:8080}

spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8

logging:
    level:
      org.springframework.web: INFO
      edu.udacity.java.nano.chat: INFO
